captainVersion: 4
services:
  # Postgres
  $$cap_appname-postgres:
    image: postgres:13
    volumes:
      - $$cap_appname-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $$cap_postgres_database_name
      POSTGRES_USER: $$cap_postgres_user
      POSTGRES_PASSWORD: $$cap_postgres_passwd
    caproverExtra:
      notExposeAsWebApp: "true"

  # Cache
  $$cap_appname-redis:
    image: redis:7
    volumes:
      - $$cap_appname-redis:/data
    caproverExtra:
      notExposeAsWebApp: "true"

  # Directus
  $$cap_appname:
    depends_on:
      - $$cap_appname-postgres
      - $$cap_appname-redis
    image: directus/directus:$$cap_directus_tag
    volumes:
      - $$cap_appname-uploads:/directus/uploads
      - $$cap_appname-extensions:/directus/extensions
      - $$cap_appname-templates:/directus/templates
    restart: always
    environment:
      SECRET: $$cap_directus_auth_secret_key

      DB_CLIENT: "pg"
      DB_HOST: srv-captain--$$cap_appname-postgres
      DB_PORT: "5432"
      DB_DATABASE: $$cap_postgres_database_name
      DB_USER: $$cap_postgres_user
      DB_PASSWORD: $$cap_postgres_passwd
      DB_POOL_MIN: "0"
      DB_POOL_MAX: "7"

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: redis://srv-captain--$$cap_appname-redis:6379

      TELEMETRY: "false"
      CORS_ENABLED: "true"
      CORS_ORIGIN: $$cap_cors_origins

      RATE_LIMITER_ENABLED: "true"

      ADMIN_EMAIL: $$cap_admin_email
      ADMIN_PASSWORD: $$cap_admin_password

      # Check more docs https://docs.directus.io/self-hosted/config-options.html#email
      EMAIL_FROM: noreply@example.com
      EMAIL_TRANSPORT: smtp
      EMAIL_SMTP_HOST: smtp.hostinger.com
      EMAIL_SMTP_PORT: 465
      EMAIL_SMTP_USER: mail@example.com
      EMAIL_SMTP_PASSWORD: yourpassword
      EMAIL_SMTP_POOL: true
      EMAIL_TEMPLATES_PATH: ./templates

      PUBLIC_URL: http://$$cap_appname.$$cap_root_domain

    caproverExtra:
      containerHttpPort: "8055"
caproverOneClickApp:
  variables:
    - description: Tag of Directus image on https://hub.docker.com/r/directus/directus/tags
      defaultValue: 10.13.1
      id: $$cap_directus_tag
      label: Directus image tag
      validRegex: /.{1,}/

    - description: Name of the Directus database instance.
      defaultValue: directus
      id: $$cap_postgres_database_name
      label: Postgres database name
      validRegex: /.{1,}/

    - description: User for the Directus database instance.
      defaultValue: directus
      id: $$cap_postgres_user
      label: Postgres user
      validRegex: /.{1,}/

    - description: User password for the Directus database instance.
      defaultValue: $$cap_gen_random_hex(16)
      id: $$cap_postgres_passwd
      label: Postgres user password
      validRegex: /^(?=.*\d).{10,}$/

    - description: Directus Auth Secret Key
      defaultValue: $$cap_gen_random_hex(16)
      id: $$cap_directus_auth_secret_key
      label: Directus Auth Secret Key
      validRegex: /^(?=.*\d).{10,}$/

    - description: Directus admin user email
      defaultValue: aristide.bruneau@gmail.com
      id: $$cap_admin_email
      label: Directus admin user email
      validRegex: /.{1,}/

    - description: Directus admin user password
      defaultValue: $$cap_gen_random_hex(8)
      id: $$cap_admin_password
      label: Directus admin user password
      validRegex: /^(?=.*\d).{8,}$/

    - description: A list of one or more URLs separated by commas
      defaultValue: http://localhost:5173
      id: $$cap_cors_origins
      label: Directus CORS Origins
      validRegex: /^(https?:\/\/(?:localhost:\d+|[\w-]+\.[\w.-]+)(?:,|$))+$/

  instructions:
    end: >
      Directus successfully deployed ! 🎉 \n
      Service is available at http://$$cap_appname.$$cap_root_domain \n
      Make sure to check the rest of the procedure to fully deploy your project.
    start: >-
      Directus is an open-source suite of software that wraps custom SQL databases with a dynamic API and intuitive Admin App.
      For more information and available options, see https://github.com/directus/docker or the official documentation at https://docs.directus.io
  displayName: "Directus"
  isOfficial: true
  description: Directus is an open-source tool for managing content across all your omni-channel digital experiences
  documentation: Taken from https://docs.directus.io/guides/installation/docker/.
